version: "3.8"

services:
  freemovies:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freemovies-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_OMDB_API_KEY=2dff02c4
    restart: unless-stopped
    volumes:
      - ./public:/app/public
